### ISSUE TITLE
Multiple lsphp versions exist in the image

### ISSUE THREAD

**Issue by ivmm** [Code-Egg/OpenLiteSpeed-Dockerfiles#1]
The openlitespeed binary installation will automatically install lsphp73. 
When installing other versions of lsphp, such as installing lsphp71, lsphp73 and lsphp71 will exist.

**Comment by Code-Egg** [comment]
Checked, and yes that binary comes with lsphp73 installed even we choose other lsphp version. But it's not a robust method to change the _in.sh file then. I'd keep it since it's no harm from what I can see. Thanks for the report.
